version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db_container123
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgress
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
